services:
  reverse-proxy:
    # official image
    image: traefik:v2.11

    # eable web ui, listen to docker
    command: --api.insecure=true --providers.docker
    expose:
      - "8888:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: rabbitmq:latest
    expose:
      - "15762:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      retries: 5
    labels:
      - "traefik.enable=true"


  marker:
    build: ./marker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]

    env_file:
      - .env
    volumes:
      - "./volumes/in:/app/in"
      - "./volumes/out:/app/out"
      - ./marker/main.py:/usr/src/app/marker/main.py
    command: python3 -u main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
    restart: always

  coordinator:
    build: ./coordinator
    env_file:
      - .env
    expose:
      - "8811:5000"
    volumes:
      - "./volumes/in:/app/in"
      - "./volumes/out:/app/out"
      - ./coordinator/coordinator.py:/app/coordinator.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coordinator.rule=PathPrefix(`/`)"
    restart: always

    command: python3 -u coordinator.py